name: Release

on:
  push:
    branches: ["build"]
  workflow_dispatch:

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.14"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: "true"

      - name: Update lockfile
        run: uv lock --upgrade

      - name: Install dependencies
        run: uv sync --group build

      - name: Run tests
        run: uv run pytest ./tests

      - name: Set datetime environment variables
        shell: pwsh
        run: |
          $now = [datetime]::UtcNow
          echo "NOW=$($now.ToString('yyyy-MM-dd HH:mm:ss')) UTC" >> $env:GITHUB_ENV
          echo "NOW_PATH=$($now.ToString('yyyy-MM-ddTHHmmssZ'))" >> $env:GITHUB_ENV
          echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
          echo "APP_VERSION=$($now.ToString('yyyy.M.dHHmmss')).dev" >> $env:GITHUB_ENV

      - name: Set release archive name as env variable
        run: echo "ARCHIVE_NAME=Proxyshop-dev_${{ env.NOW_PATH }}_${{ env.SHORT_SHA }}.zip" >> $env:GITHUB_ENV

      - name: Define app version
        run: echo "version='${{ env.APP_VERSION }}.dev'" > __VERSION__.py

      - name: Build app
        run: uv run pyinstaller -n Proxyshop --onefile --icon "./src/img/favicon.ico" --distpath "./dist" --console --add-data "src/gui/qml:src/gui/qml" --add-data "src/img/favicon.ico:src/img/favicon.ico" main.py

      - name: Copy fonts
        run: cp -Path "./fonts" -Destination "./dist" -Recurse -Force

      - name: Copy plugins
        run: cp -Path "./plugins" -Destination "./dist" -Recurse -Force

      - name: Copy templates
        run: cp -Path "./templates" -Destination "./dist" -Recurse -Force

      - name: Copy data
        # Here ./dist/src doesn't exist yet so cp only copies source directory contents
        # to the newly created ./dist/src, so we have to specify data as the target directory
        run: cp -Path "./src/data" -Destination "./dist/src/data" -Recurse -Force

      - name: Copy img
        # Here ./dist/src already exists so cp copies the whole source directory
        # and not just its contents
        run: cp -Path "./src/img" -Destination "./dist/src" -Recurse -Force

      - name: Copy README
        run: cp "./README.md" -Destination "./dist" -Force

      - name: Copy LICENSE
        run: cp "./LICENSE.md" -Destination "./dist" -Force

      - name: Zip files
        run: 7z a "./${{ env.ARCHIVE_NAME }}" "./dist/*"

      - name: Create release tag
        run: |
          git tag -f ${{ env.NOW_PATH }}
          git push origin ${{ env.NOW_PATH }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: "${{ env.NOW }} ${{ env.SHORT_SHA }}"
          body: |
            > [!IMPORTANT]
            > If you are updating from version **2026.5.112201** or earlier you should reinstall the **Proxyglyph** font in order to benefit from its latest changes.
            This is an unofficial development release of Proxyshop. While some testing is usually conducted on the changes that are integrated to the release, bugs might still slip through. If you encounter problems, you may [open an issue](https://github.com/pappnu/Proxyshop/issues).

            After updating from an earlier release make sure to check that your PSD files (via **Updater** in app) and plugins (via the way you acquired it, e.g. the plugin's GitHub page, if it has one) are up to date as well.
          prerelease: true
          files: ${{ env.ARCHIVE_NAME }}
          tag_name: ${{ env.NOW_PATH }}
          fail_on_unmatched_files: true
          generate_release_notes: true

  cleanup:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Delete old releases
        run: gh release list --json tagName --jq '.[] | .tagName' | tail -n+7 | xargs -r -n 1 gh release delete --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
